FROM node:18-alpine as build-stage

ARG APP_API_URL

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

ENV VITE_APP_API_URL=$APP_API_URL

RUN npm run build

FROM nginx

ARG FRONTEND_PORT

COPY --from=build-stage /app/dist /usr/share/nginx/html/

RUN echo "\ 
server {\
	listen 3000 default_server;\
    root /usr/share/nginx/html/;\
    index /index.html;\
\
    location / {\
        try_files \$uri \$uri/ /index.html;\
    }\
}" > /etc/nginx/conf.d/default.conf

EXPOSE 3000
