version: "3.8"

services:
  backend:
    build: ./backend
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      CORS_ALLOWED_ORIGINS: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REPOS_FOLDER: /repos
      PYTHONUNBUFFERED: 1
      SERVER_TEST_MODE: ${SERVER_TEST_MODE}
      PRODUCTION: "0"
    volumes:
      - ./backend/src:/app/src
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_APP_API_URL: ${BACKEND_URL}
    volumes:
      - ./frontend/src:/app/src
